# Generated by Django 3.1.2 on 2020-10-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='x')),
                ('Y', models.FloatField(help_text='y')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=25)),
                ('Date', models.DateField(blank=True, help_text='Date')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Choices of Age', max_length=25, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Choices of Fur Color', max_length=25, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above_Ground')], help_text='Choices of Location', max_length=25, null=True)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific Location', max_length=25, null=True)),
                ('Running', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Choices of Running', max_length=25, null=True)),
                ('Chasing', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Choices of Chasing', max_length=25, null=True)),
                ('Climbing', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Choices of Climbing', max_length=25, null=True)),
                ('Eating', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Choices of Eating', max_length=25, null=True)),
                ('Foraging', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Choices of Foraging', max_length=25, null=True)),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=50, null=True)),
                ('Kuks', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Kuks', max_length=25, null=True)),
                ('Quaas', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Quaas', max_length=25, null=True)),
                ('Moans', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Moans', max_length=25, null=True)),
                ('Tail_flags', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Tail Flags', max_length=25, null=True)),
                ('Tail_twitches', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Tail Twitches', max_length=25, null=True)),
                ('Approaches', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Approaches', max_length=25, null=True)),
                ('Indifferent', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Indifferent', max_length=25, null=True)),
                ('Runs_from', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], help_text='Runs From', max_length=25, null=True)),
            ],
        ),
    ]
