# Generated by Django 3.1.2 on 2020-10-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Y',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='X',
            new_name='Longitude',
        ),
    ]
